# Generated by Django 3.1.7 on 2021-05-03 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_player_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.TextField(default='bRbNbBbQbKbBbNbR\n    bpbpbpbpbpbpbpbp\n    ----------------\n    ----------------\n    ----------------\n    ----------------\n    wpwpwpwpwpwpwpwp\n    wRwNwBwQwKwBwNwR')),
                ('white_to_move', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
    ]
