# Generated by Django 3.1.7 on 2021-05-03 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_gamestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.AddField(
            model_name='match',
            name='black_player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='black_player', to='matches.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='white_player',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to='matches.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='board',
            field=models.TextField(default='bRbNbBbQbKbBbNbRbpbpbpbpbpbpbpbp----------------------------------------------------------------wpwpwpwpwpwpwpwpwRwNwBwQwKwBwNwR'),
        ),
    ]
