# Generated by Django 3.1.7 on 2021-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20210503_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
